Want to test something

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,4 +1,5 @@
 stages:
+  - check
   - documentation
   - quality
   - build
@@ -8,6 +9,17 @@ stages:
 variables:
   GIT_STRATEGY: clone
   TIMEOUT: 10m
+
+check_plantuml:
+  stage: check
+  script:
+    - |
+      if ! command -v plantuml &> /dev/null; then
+        echo "Error: PlantUML is not installed."
+        exit 1
+      else
+        echo "PlantUML is installed!"
+      fi
 
 docs:
   stage: documentation
